XCopy VideoOS.Platform.SDK.dll %1 /Y
XCopy VideoOS.Platform.SDK.Export.dll %1 /Y
XCopy DBExporterClientMW.dll %1 /Y
XCopy AVIExporterClientMW.dll %1 /Y
XCopy boost_*.dll %1 /Y
XCopy icu*.dll %1 /Y
XCopy imv*.dll %1 /Y
XCopy j2KCorex.dll %1 /Y
XCopy Mm025.dll %1 /Y
XCopy mfc1*.dll %1 /Y
XCopy mfcm1*.dll %1 /Y
XCopy msvcp1*.dll %1 /Y
XCopy msvcr1*.dll %1 /Y
XCopy python*.dll %1 /Y
XCopy xerces-c*.dll %1 /Y
XCopy xqilla*.dll %1 /Y
XCopy VideoOS.Platform.Primitives.dll %1 /Y
XCopy VideoOS.Database*.dll %1 /Y
XCopy VideoOS.Toolkit*.dll %1 /Y
XCopy VideoOS.MM025Utility.dll %1 /Y
XCopy Toolkit*.dll %1 /Y
XCopy CoreToolkits.dll %1 /Y
